// 100 apellidos en un arreglo
var salida = "";
const apellidosMexicanos = [
    "García",
    "Hernández",
    "Martínez",
    "López",
    "González",
    "Pérez",
    "Rodríguez",
    "Sánchez",
    "Ramírez",
    "Cruz",
    "Flores",
    "Gómez",
    "Morales",
    "Vázquez",
    "Jiménez",
    "Reyes",
    "Torres",
    "Díaz",
    "Gutiérrez",
    "Ruiz",
    "Mendoza",
    "Aguilar",
    "Castillo",
    "Ortiz",
    "Romero",
    "Álvarez",
    "Chávez",
    "Rivera",
    "Juárez",
    "Moreno",
    "Rojas",
    "Guerrero",
    "Medina",
    "Salazar",
    "Herrera",
    "Cabrera",
    "Soto",
    "Contreras",
    "Castro",
    "Silva",
    "Delgado",
    "Luna",
    "Velázquez",
    "Fuentes",
    "Pacheco",
    "Domínguez",
    "Valdez",
    "Campos",
    "Cortés",
    "Peña",
    "Ibarra",
    "Nava",
    "Gallegos",
    "Rosales",
    "Acosta",
    "Figueroa",
    "Escobar",
    "Cárdenas",
    "Ochoa",
    "Zúñiga",
    "Padilla",
    "Treviño",
    "Montoya",
    "Arellano",
    "Villanueva",
    "Solís",
    "Esparza",
    "Meza",
    "Coronado",
    "Bustos",
    "Tapia",
    "Barrera",
    "Ayala",
    "Rocha",
    "Valencia",
    "Benítez",
    "Arredondo",
    "Carrillo",
    "Castañeda",
    "Franco",
    "Lozano",
    "Quintana",
    "Rangel",
    "Zamora",
    "Macías",
    "Bautista",
    "Camacho",
    "Cisneros",
    "Miranda",
    "Palacios",
    "Beltrán",
    "Leyva",
    "Olvera",
    "Peralta",
    "Saucedo",
    "Trujillo",
    "Murillo",
    "Pineda",
    "Godínez",
    "De la Cruz"
];
const apellidosJaponeses = [
    "NULL",
    "Suzuki",
    "Takahashi",
    "Tanaka",
    "Watanabe",
    "Ito",
    "Yamamoto",
    "Nakamura",
    "Kobayashi",
    "Kato",
    "Yoshida",
    "Yamada",
    "Sasaki",
    "Yamaguchi",
    "Matsumoto",
    "Inoue",
    "Kimura",
    "Hayashi",
    "Shimizu",
    "Yamazaki",
    "Mori",
    "Abe",
    "Ikeda",
    "Hashimoto",
    "Yamashita",
    "Ishikawa",
    "Nakajima",
    "Maeda",
    "Fujita",
    "Ogawa",
    "Goto",
    "Okada",
    "Hasegawa",
    "Murakami",
    "Kondo",
    "Ishii",
    "Saito",
    "Sakamoto",
    "Endo",
    "Aoki",
    "Fujii",
    "Nishimura",
    "Fukuda",
    "Ota",
    "Miura",
    "Okamoto",
    "Matsuda",
    "Nakagawa",
    "Kaneko",
    "Nakano",
    "Harada",
    "Ono",
    "Tamura",
    "Takeuchi",
    "Sugiyama",
    "Ando",
    "Ueda",
    "Imai",
    "Maruyama",
    "Takeda",
    "Fujimoto",
    "Arai",
    "Nakayama",
    "Otsuka",
    "Hirano",
    "Kubo",
    "Sugawara",
    "Matsui",
    "Chiba",
    "Iwasaki",
    "Sakai",
    "Kawaguchi",
    "Noguchi",
    "Kuroda",
    "Hattori",
    "Araki",
    "Shibata",
    "Matsuura",
    "Kanai",
    "Yokoyama",
    "Hori",
    "Oshima",
    "Honda",
    "Kishi",
    "Tanimoto",
    "Kojima",
    "Tsuchiya",
    "Nomura",
    "Kumagai",
    "Kiriyama",
    "Shiraishi",
    "Uemura",
    "Kagawa",
    "Nagata",
    "Tokunaga",
    "Morita",
    "Yasuda",
    "Minami",
    "Ohashi",
    "Komatsu"
];
const nombresMexicanos = [
    "Juan",
    "José",
    "Luis",
    "Carlos",
    "Jorge",
    "Miguel",
    "Jesús",
    "Manuel",
    "Antonio",
    "Francisco",
    "Pedro",
    "Alejandro",
    "Daniel",
    "Fernando",
    "Ricardo",
    "Roberto",
    "Eduardo",
    "Javier",
    "Raúl",
    "Mario",
    "Sergio",
    "Arturo",
    "Alfonso",
    "Andrés",
    "Diego",
    "Emiliano",
    "Ángel",
    "Víctor",
    "Enrique",
    "Ramón",
    "Guillermo",
    "Óscar",
    "Pablo",
    "Iván",
    "Adrián",
    "Héctor",
    "Martín",
    "Salvador",
    "Samuel",
    "Leonardo",
    "Ana",
    "María",
    "Guadalupe",
    "Juana",
    "Rosa",
    "Patricia",
    "Verónica",
    "Laura",
    "Claudia",
    "Carmen",
    "Silvia",
    "Teresa",
    "Leticia",
    "Gabriela",
    "Alejandra",
    "Daniela",
    "Adriana",
    "Mónica",
    "Beatriz",
    "Julia",
    "Andrea",
    "Karla",
    "Paola",
    "Fernanda",
    "Sofía",
    "Valeria",
    "Mariana",
    "Natalia",
    "Camila",
    "Renata",
    "Ximena",
    "Lucía",
    "Fátima",
    "Araceli",
    "Liliana",
    "Brenda",
    "Yesenia",
    "Irma",
    "Yolanda",
    "Lidia",
    "Susana",
    "Norma",
    "Esther",
    "Rebeca",
    "Miriam",
    "Lorena",
    "Diana",
    "Elisa",
    "Elena",
    "Alicia",
    "César",
    "Cristian",
    "Brandon",
    "Kevin",
    "Jonathan",
    "Bryan",
    "Alexis",
    "Uriel",
    "Gael",
    "Mateo"
];
const nombresAmericanos = [
    "James",
    "John",
    "Robert",
    "Michael",
    "William",
    "David",
    "Richard",
    "Joseph",
    "Thomas",
    "Charles",
    "Christopher",
    "Daniel",
    "Matthew",
    "Anthony",
    "Mark",
    "Donald",
    "Steven",
    "Paul",
    "Andrew",
    "Joshua",
    "Kenneth",
    "Kevin",
    "Brian",
    "George",
    "Edward",
    "Ronald",
    "Timothy",
    "Jason",
    "Jeffrey",
    "Ryan",
    "Jacob",
    "Gary",
    "Nicholas",
    "Eric",
    "Stephen",
    "Jonathan",
    "Larry",
    "Justin",
    "Scott",
    "Brandon",
    "Benjamin",
    "Samuel",
    "Gregory",
    "Alexander",
    "Patrick",
    "Jack",
    "Dennis",
    "Jerry",
    "Tyler",
    "Aaron",
    "Henry",
    "Douglas",
    "Jose",
    "Adam",
    "Nathan",
    "Zachary",
    "Walter",
    "Kyle",
    "Harold",
    "Carl",
    "Jeremy",
    "Keith",
    "Roger",
    "Gerald",
    "Ethan",
    "Christian",
    "Austin",
    "Noah",
    "Logan",
    "Olivia",
    "Emma",
    "Ava",
    "Sophia",
    "Isabella",
    "Mia",
    "Charlotte",
    "Amelia",
    "Harper",
    "Evelyn",
    "Abigail",
    "Emily",
    "Elizabeth",
    "Sofia",
    "Madison",
    "Scarlett",
    "Victoria",
    "Aria",
    "Grace",
    "Chloe",
    "Camila",
    "Penelope",
    "Riley",
    "Layla",
    "Lillian",
    "Nora",
    "Zoey",
    "Hannah",
    "Lily"
];

// Funciones de generación
function generar() {
    var opcion = document.getElementById("opcion").value;

    switch (opcion) {
        case "1": generarSQL(); break;
        case "2": generarSQL(); break;
        case "3": generarCSV(); break;
        case "4": generarJSON(); break;
    }
}
function generarSQL() {
    salida = "INSERT INTO alumnos VALUES <br>";
    var matricula = 224200000;
    var registros = 0;
    registros = document.getElementById('registros').value;

    for (let i = 0; i < registros; i++) {

        let app2_num = Math.floor(Math.random() * apellidosJaponeses.length);
        let app2_txt = app2_num !== 0 ? `UPPER('${apellidosJaponeses[app2_num]}')` : `${apellidosJaponeses[app2_num]}`;

        salida += `(${matricula + i}, UPPER('${apellidosMexicanos[Math.floor(Math.random() * apellidosMexicanos.length)]}'), ${app2_txt}, UPPER('${nombresMexicanos[Math.floor(Math.random() * apellidosMexicanos.length)]}${Math.round(Math.random()) == 1 ? ` ${nombresAmericanos[Math.floor(Math.random() * apellidosMexicanos.length)]}` : ""}'), 'a${matricula + i}@unison.mx')${i != registros - 1 ? "," : ";"}<br>`;

    }
    document.getElementById("salida").innerHTML = salida;
}
function generarCSV() {
    salida = "expediente,apellido1,apellido2,nombres,correo<br>";
    var matricula = 224200000;
    var registros = 0;
    registros = document.getElementById('registros').value;

    for (let i = 0; i < registros; i++) {

        let app2_num = Math.floor(Math.random() * apellidosJaponeses.length);
        let app2_txt = app2_num !== 0 ? `${apellidosJaponeses[app2_num]}` : `${apellidosJaponeses[app2_num]}`;

        salida += `${matricula + i},${apellidosMexicanos[Math.floor(Math.random() * apellidosMexicanos.length)]},${app2_txt},${nombresMexicanos[Math.floor(Math.random() * apellidosMexicanos.length)]}${Math.round(Math.random()) == 1 ? ` ${nombresAmericanos[Math.floor(Math.random() * apellidosMexicanos.length)]}` : ""},a${matricula + i}@unison.mx<br>`;

    }
    document.getElementById("salida").innerHTML = salida;
}
function generarJSON() {
    salida = "[<br>";
    var matricula = 224200000;
    var registros = 0;
    registros = document.getElementById('registros').value;

    for (let i = 0; i < registros; i++) {

        let app2_num = Math.floor(Math.random() * apellidosJaponeses.length);
        let app2_txt = app2_num !== 0 ? `${apellidosJaponeses[app2_num]}` : `${apellidosJaponeses[app2_num]}`;

        salida += `    {
        "expediente": ${matricula + i},
        "apellido1": "${apellidosMexicanos[Math.floor(Math.random() * apellidosMexicanos.length)]}",
        "apellido2": "${app2_txt}",
        "nombres": "${nombresMexicanos[Math.floor(Math.random() * apellidosMexicanos.length)]}${Math.round(Math.round()) == 1 ? ` ${nombresAmericanos[Math.floor(Math.random() * apellidosMexicanos.length)]}` : ""}",
        "correo": "a${matricula + i}@unison.mx"
    }${i != registros - 1 ? "," : ""}<br>`;

    }
    salida += "]";
    document.getElementById("salida").innerHTML = salida;
}
function guardarArchivo() {
    var var1 = document.createElement("a");
    salida = salida.replaceAll("<br>", "\r\n");
    var1.setAttribute("href", "data:text/plain;charset=UTF-8," + encodeURIComponent(salida));
    var1.setAttribute("download", "sistema_escolar.sql");

    var opcion = document.getElementById("opcion").value;

    switch (opcion) {
        case "1": var1.setAttribute("download", "sistema_escolar.sql"); alert("Generando archivo SQL"); break;
        case "2": var1.setAttribute("download", "sistema_escolar.sql"); alert("Generando archivo SQL"); break;
        case "3": var1.setAttribute("download", "sistema_escolar.csv"); alert("Generando archivo CSV"); break;
        case "4": var1.setAttribute("download", "sistema_escolar.json"); alert("Generando archivo JSON"); break;
    }

    var1.style.display = "none";
    document.body.appendChild(var1);
    var1.click();
    document.body.removeChild(var1);
}